[package]
name = "rust_v"
version = "0.1.0"
authors = ["Julius Oeftiger <j.oeftiger@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ultraviolet = ""
image = "^0.23.10"
show-image = { version = "^0.6.4", features = ["image", "save"] }

[profile.release]
codegen-units = 1
opt-level = 3
lto = true
incremental = true

[profile.release.package."*"]
codegen-units = 1
opt-level = 3
