[package]
name = "rust_v"
version = "0.1.0"
authors = ["Julius Oeftiger <j.oeftiger@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "^2.33.3"
extend = "^0.3.0"
rand = "^0.7.3"
serde = "^1.0.116"
serde_json = "^1.0.57"
ultraviolet = { version = "^0.7.1", features = ["serde"] }

[dev-dependencies]
criterion = "^0.3.3"

[profile.release]
opt-level = 3
lto = true

[profile.dev.package."*"]
opt-level = 3

[profile.release.package."*"]
opt-level = 3
