[package]
name = "rust_v"
version = "0.1.0"
authors = ["Julius Oeftiger <j.oeftiger@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ultraviolet = "^0.7.1"
serde_json = "^1.0.57"
serde = "^1.0.116"
clap = "^2.33.3"
extend = "^0.3.0"

[dev-dependencies]
criterion = "^0.3.3"
